## Cauculating Cosine Similarity in Python

In [1]:
import numpy as np

A = np.array([1 , 2])
B = np.array([2 , 3])

cos_sim = np.dot(A , B)/(np.linalg.norm(A) * np.linalg.norm(B))
print(cos_sim)

0.9922778767136677

In [2]:
A = np.array([3 , 45 , 7 , 2])
B = np.array([2 , 54 , 13 , 15])

cos_sim = np.dot(A , B)/(np.linalg.norm(A) * np.linalg.norm(B))
print(round(cos_sim , 3))

0.972

In [6]:
import pandas as pd

tag = pd.read_csv("app/data/tag.csv")

In [7]:
tag.head()

   userId  movieId            tag            timestamp
0      18     4141    Mark Waters  2009-04-24 18:19:40
1      65      208      dark hero  2013-05-10 01:41:18
2      65      353      dark hero  2013-05-10 01:41:19
3      65      521  noir thriller  2013-05-10 01:39:43
4      65      592      dark hero  2013-05-10 01:41:18

In [57]:
tag.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 465564 entries, 0 to 465563
Data columns (total 4 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   userId     465564 non-null  int64
 1   movieId    465564 non-null  int64
 2   tag        465548 non-null  object
 3   timestamp  465564 non-null  object
dtypes: int64(2), object(2)
memory usage: 14.2+ MB

In [8]:
genome_tags = pd.read_csv("genome_tags.csv")

In [9]:
genome_tags.head()

   tagId           tag
0      1           007
1      2  007 (series)
2      3  18th century
3      4         1920s
4      5         1930s

In [55]:
moive_data = pd.read_csv("app/data/movie.csv")

In [56]:
moive_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27278 entries, 0 to 27277
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   movieId  27278 non-null  int64
 1   title    27278 non-null  object
 2   genres   27278 non-null  object
dtypes: int64(1), object(2)
memory usage: 639.5+ KB

In [12]:
moive_data.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [53]:
movies = pd.read_csv('app/data/movie.csv').sample(frac=0.4, random_state=42)

In [13]:
moive_data['genres'] = moive_data['genres'].str.replace('|' , ', ' , regex = False)

In [54]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10911 entries, 12922 to 2132
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   movieId  10911 non-null  int64
 1   title    10911 non-null  object
 2   genres   10911 non-null  object
dtypes: int64(1), object(2)
memory usage: 341.0+ KB

In [14]:
moive_data

,movieId,title,genres
0,1,Toy Story (1995),"Adventure, Animation, Children, Comedy, Fantasy"
1,2,Jumanji (1995),"Adventure, Children, Fantasy"
2,3,Grumpier Old Men (1995),"Comedy, Romance"
3,4,Waiting to Exhale (1995),"Comedy, Drama, Romance"
4,5,Father of the Bride Part II (1995),Comedy
...,...,...,...
27273,131254,Kein Bund für's Leben (2007),Comedy
27274,131256,"Feuer, Eis & Dosenbier (2002)",Comedy
27275,131258,The Pirates (2014),Adventure
27276,131260,Rentun Ruusu (2001),(no genres listed)
27277,131262,Innocence (2014),"Adventure, Fantasy, Horror"

In [15]:
df = pd.merge(moive_data , tag , on="movieId")

In [16]:
df.head()

,movieId,title,genres,userId,tag,timestamp
0,1,Toy Story (1995),"Adventure, Animation, Children, Comedy, Fantasy",1644,Watched,2014-12-04 23:44:40
1,1,Toy Story (1995),"Adventure, Animation, Children, Comedy, Fantasy",1741,computer animation,2007-07-08 13:59:15
2,1,Toy Story (1995),"Adventure, Animation, Children, Comedy, Fantasy",1741,Disney animated feature,2007-07-08 22:21:47
3,1,Toy Story (1995),"Adventure, Animation, Children, Comedy, Fantasy",1741,Pixar animation,2007-07-08 22:46:10
4,1,Toy Story (1995),"Adventure, Animation, Children, Comedy, Fantasy",1741,TÃ©a Leoni does not star in this movie,2009-06-15 19:19:33

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 465564 entries, 0 to 465563
Data columns (total 6 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   movieId    465564 non-null  int64
 1   title      465564 non-null  object
 2   genres     465564 non-null  object
 3   userId     465564 non-null  int64
 4   tag        465548 non-null  object
 5   timestamp  465564 non-null  object
dtypes: int64(2), object(4)
memory usage: 21.3+ MB

In [18]:
df['genres'] = df['genres'].str.replace(', ' , ' ' , regex=False).str.lower()

In [19]:
df['tag'] = df['tag'].str.lower()

In [25]:
df['tag'][0]

'watched'

In [21]:
df.shape

(465564, 6)

In [22]:
df['tag'] = df['tag'].fillna('')

In [30]:
movie_content = df.groupby(['movieId' , 'title' , 'genres'])['tag'].apply(lambda x: ' '.join(x)).reset_index()

In [31]:
movie_content.head()

,movieId,title,genres,tag
0,1,Toy Story (1995),adventure animation children comedy fantasy,watched computer animation disney animated fea...
1,2,Jumanji (1995),adventure children fantasy,time travel adapted from:book board game child...
2,3,Grumpier Old Men (1995),comedy romance,old people that is actually funny sequel fever...
3,4,Waiting to Exhale (1995),comedy drama romance,chick flick revenge characters chick flick cha...
4,5,Father of the Bride Part II (1995),comedy,diane keaton family sequel steve martin weddin...

In [32]:
movie_content['metadata'] = movie_content['genres'] + ' ' + movie_content['tag']

In [33]:
movie_content.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19545 entries, 0 to 19544
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   movieId   19545 non-null  int64
 1   title     19545 non-null  object
 2   genres    19545 non-null  object
 3   tag       19545 non-null  object
 4   metadata  19545 non-null  object
dtypes: int64(1), object(4)
memory usage: 763.6+ KB

In [34]:
movie_content['metadata'][1]

'adventure children fantasy time travel adapted from:book board game childhood recaptured game herds of cgi animals scary see also:zathura time time travel board game fantasy robin williams scary time travel robin williams joe johnston robin williams kid flick jungle robin williams board game robin williams animals lebbat robin williams time travel adventure robin williams children fantasy robin williams dynamic cgi action kirsten dunst robin williams robin williams fantasy kid flick animals animals fantasy for children fantasy adapted from:book childish children kid flick time travel joe johnston fantasy robin williams time travel animals board game children fantasy kirsten dunst robin williams time travel board game time travel children kid flick filmed in bc fantasy robin williams animals bad cgi based on a book board game chris van allsburg robin williams robin williams game magic board game monkey adapted from:book animals bad cgi based on a book board game childhood recaptured children chris van allsburg fantasy filmed in bc jungle kid flick kirsten dunst monkey robin williams saturn award (best special effects) saturn award (best supporting actress) scary time time travel animals based on a book magic board game monkey robin williams time travel animals childhood recaptured herds of cgi animals kirsten dunst robin williams fantasy robin williams scary time travel clv bad cgi horrifying (but not horror genre) kirsten dunst magic board game monkey not for kids fantasy animals fantasy robin williams scary'

## Step 2: Vectorization
#### We use CountVectorizer to convert those genre strings into a matrix of numbers

In [35]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [36]:
from sklearn.model_selection import train_test_split

X_train , y_train = train_test_split(movie_content , test_size=0.5 , random_state=42)

In [37]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9772 entries, 14909 to 15795
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   movieId   9772 non-null   int64
 1   title     9772 non-null   object
 2   genres    9772 non-null   object
 3   tag       9772 non-null   object
 4   metadata  9772 non-null   object
dtypes: int64(1), object(4)
memory usage: 458.1+ KB

In [38]:
X_train.head()

,movieId,title,genres,tag,metadata
14909,93766,Wrath of the Titans (2012),action adventure fantasy imax,action adventure cgi 3d action adventure cgi d...,action adventure fantasy imax action adventure...
16976,106521,Beyond the Time Barrier (1960),sci-fi,time travel,sci-fi time travel
11222,64499,Che: Part One (2008),drama war,benicio del toro steven soderbergh based on a ...,drama war benicio del toro steven soderbergh b...
16540,104054,"Redhead from Wyoming, The (1953)",western,politics redhead western,western politics redhead western
5844,6885,In the Cut (2003),crime drama mystery romance thriller,protagonist is a teacher serial killer `murder...,crime drama mystery romance thriller protagoni...

In [39]:
X_train = X_train.reset_index(drop=True)

In [40]:
X_train.head()

,movieId,title,genres,tag,metadata
0,93766,Wrath of the Titans (2012),action adventure fantasy imax,action adventure cgi 3d action adventure cgi d...,action adventure fantasy imax action adventure...
1,106521,Beyond the Time Barrier (1960),sci-fi,time travel,sci-fi time travel
2,64499,Che: Part One (2008),drama war,benicio del toro steven soderbergh based on a ...,drama war benicio del toro steven soderbergh b...
3,104054,"Redhead from Wyoming, The (1953)",western,politics redhead western,western politics redhead western
4,6885,In the Cut (2003),crime drama mystery romance thriller,protagonist is a teacher serial killer `murder...,crime drama mystery romance thriller protagoni...

In [41]:
cv = CountVectorizer(stop_words='english')
count_vec = cv.fit_transform(movie_content['metadata'])

In [42]:
count_vec

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 321382 stored elements and shape (19545, 23865)>

In [43]:
print(count_vec.toarray()[0])

[0 0 0 ... 0 0 0]

In [44]:
cosine_sim = cosine_similarity(count_vec , count_vec)

In [45]:
cosine_sim

array([[1.        , 0.10200443, 0.04857212, ..., 0.        , 0.        ,
        0.03430839],
       [0.10200443, 1.        , 0.00295731, ..., 0.        , 0.        ,
        0.01823009],
       [0.04857212, 0.00295731, 1.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 1.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 1.        ,
        0.        ],
       [0.03430839, 0.01823009, 0.        , ..., 0.        , 0.        ,
        1.        ]], shape=(19545, 19545))

In [46]:
# create a mapping of movie titles to their index in the dataframe

indices = pd.Series(movie_content.index , index=movie_content['title']).drop_duplicates()

In [47]:
indices

title
Toy Story (1995)                                     0
Jumanji (1995)                                       1
Grumpier Old Men (1995)                              2
Waiting to Exhale (1995)                             3
Father of the Bride Part II (1995)                   4
                                                 ...
Dinotopia: Quest for the Ruby Sunstone (2005)    19540
Playground (2009)                                19541
Vietnam in HD (2011)                             19542
Parallels (2015)                                 19543
The Pirates (2014)                               19544
Length: 19545, dtype: int64

In [48]:
def get_recommendation(title , cosine_sim = cosine_sim):
    if title not in indices:
        return "Movie Not Found"

    # Get the index of the movie that matches the title
    idx = indices[title]
    

    # Get the pairwise similarity scores of all movies with that movie
    sim_score = list(enumerate(cosine_sim[idx]))

    sim_score = sorted(sim_score , key=lambda x: x[1] , reverse=True)

    sim_score = sim_score[1:7]

    movie_indices = [i[0] for i in sim_score]

    title = movie_content['title'].iloc[movie_indices]
    
    return title

In [134]:
get_recommendation("Toy Story (1995)")

2603       Toy Story 2 (1999)
1919     Bug's Life, A (1998)
4428           Ice Age (2002)
4133    Monsters, Inc. (2001)
5404      Finding Nemo (2003)
9909       Ratatouille (2007)
Name: title, dtype: object

In [64]:
score = sorted(score , key=lambda x: x[1] , reverse=True)

In [69]:
s = score[1:10]

In [72]:
for i in s:
    print(i[0])

2223
4790
2922
9395
2254
651
8255
6752
5256

In [79]:
titles = X_train['title'].iloc[2223]

In [80]:
titles

'Legend of Hercules, The (2014)'

In [106]:
!pip install rapidfuzz

Requirement already satisfied: rapidfuzz in c:\users\dhang\anaconda3\lib\site-packages (3.14.3)

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [107]:
all_titles = indices.index.tolist()

In [160]:
all_titles

['Wrath of the Titans (2012)',
 'Beyond the Time Barrier (1960)',
 'Che: Part One (2008)',
 'Redhead from Wyoming, The (1953)',
 'In the Cut (2003)',
 'Are You Here (2014)',
 'Hidden Agenda (1990)',
 'Cercle Rouge, Le (Red Circle, The) (1970)',
 'Video Games: The Movie (2014)',
 'City of Pirates (La ville des pirates) (1983)',
 'Revenant, The (2009)',
 'Sun Kissed (2012)',
 'Touch of Class, A (1973)',
 'Potiche (2010)',
 'Centennial (1978)',
 'Wheel, The (La Roue) (1923)',
 'Last Taboo, The (2013)',
 'Ali Baba Goes to Town (1937)',
 'Brooklyn Castle (2012)',
 'Big Time Operators (Smallest Show on Earth, The) (1957)',
 'Oversimplification of Her Beauty, An (2012)',
 'Tarnished Angels, The (1958)',
 'Viva Zapata! (1952)',
 '88 Minutes (2008)',
 '12 Angry Men (1957)',
 'His Kind of Woman (1951)',
 'Metropolis (2001)',
 'Mississippi Burning (1988)',
 'Hired Hand, The (1971)',
 'Staying Alive (1983)',
 'My Name Is Nobody (Il Mio nome è Nessuno) (1973)',
 'Pirate, The (1948)',
 '8 ½ Women (a.k.a. 8 1/2 Women) (a.k.a. Eight and a Half Women) (1999)',
 'Sound Barrier, The (1952)',
 'Blood Simple (1984)',
 'November Man, The (2014)',
 'Bellboy, The (1960)',
 'Curious George (2006)',
 'Polar Bear King, The (Kvitebjørn Kong Valemon) (1991)',
 'Harakiri (Seppuku) (1962)',
 'On the Beach (1959)',
 'In a World... (2013)',
 'American Nightmare, The (2000)',
 'American President, The (1995)',
 'Preaching to the Perverted (1997)',
 'Pusher II: With Blood on My Hands (2004)',
 'Wedding Singer, The (1998)',
 "Aujourd'hui (2012)",
 'Aliyah (Alyah) (2012)',
 'Particle Fever (2013)',
 'Rules of Attraction, The (2002)',
 'Waiting for Superman (2010)',
 'Jack-Jack Attack (2005)',
 'Ice Rink, The (La patinoire) (1998)',
 'My Tutor (1983)',
 'Old Fashioned Way, The (1934)',
 'Shy People (1987)',
 "Knockin' on Heaven's Door (1997)",
 'Life Less Ordinary, A (1997)',
 'Earth to Echo (2014)',
 'Calendar Girl (1993)',
 'People vs. Larry Flynt, The (1996)',
 'Thirteen Days (2000)',
 'Germinal (1993)',
 'Mission: Impossible - Ghost Protocol (2011)',
 'Perfect Plan, A (Plan parfait, Un) (2012)',
 'View from the Top, A (2003)',
 'Ruby Sparks (2012)',
 'Fifth Element, The (1997)',
 'Lone Ranger and the Lost City of Gold, The (1958)',
 'Little Thief, The (La petite voleuse) (1988)',
 'Hotel de Love (1996)',
 'Last September, The (1999)',
 'Rio Grande (1950)',
 'Night Flier (1997)',
 'Sweeney Todd: The Demon Barber of Fleet Street (2007)',
 'Outbreak (1995)',
 'Game Over: Kasparov and the Machine (2003)',
 'Trotsky, The (2009)',
 'Boys & Girl from County Clare, The (a.k.a. The Boys from County Clare) (2003)',
 'Ladykillers, The (2004)',
 'Pete Seeger: The Power of Song (2007)',
 'Young at Heart (a.k.a. Young@Heart) (2007)',
 'Garden Party (2008)',
 "You Can't Win 'Em All (1970)",
 'The Questor Tapes (1974)',
 'Marley & Me (2008)',
 'All Over Me (1997)',
 'Vault of Horror, The (1973)',
 'Ballast (2008)',
 'Neil Young Journeys (2012)',
 'Ask the Dust (2006)',
 'Prom Night in Mississippi (2009)',
 'Autumn Ball (Sügisball) (2007)',
 'Sonatine (Sonachine) (1993)',
 'Dick Figures: The Movie (2013)',
 'In the Mirror of Maya Deren (Im Spiegel der Maya Deren) (2002)',
 'Dead of Night (1945)',
 'Once Upon a Forest (1993)',
 'Parents (1989)',
 'Beyond Therapy (1987)',
 'Jet Pilot (1957)',
 'Four Horsemen (2012)',
 'On the Outs (2004)',
 'Across the Tracks (1991)',
 'Song of the Thin Man (1947)',
 'Must Have Been Love (2012)',
 'Beautiful Person, The (La belle personne) (2008)',
 'Deconstructing Harry (1997)',
 'Bad Boys (1983)',
 'Tootsie (1982)',
 'Act of Killing, The (2012)',
 'Ladykillers, The (1955)',
 'Hamlet (2009)',
 'Descent: Part 2, The (2009)',
 'Big Top Pee-Wee (1988)',
 'Music Lovers, The (1970)',
 'Sudden Fear (1952)',
 'I, the Worst of All (Yo, la peor de todas) (1990)',
 'AM1200 (2008)',
 'Fortress (1992)',
 'Blue Ruin (2013)',
 'Heroes for Sale (1933)',
 'Man Without a Past, The (Mies vailla menneisyyttä) (2002)',
 'Control Room (2004)',
 'Sleep Room, The (1998)',
 'Re-cycle (Gwai wik) (2006)',
 'Separation, A (Jodaeiye Nader az Simin) (2011)',
 'High Sierra (1941)',
 'Rocks (Rad, Das) (2003)',
 'Young Detective Dee: Rise of the Sea Dragon (Di Renjie: Shen du long wang) (2013)',
 'Sabretooth (2002)',
 "When You're Strange (2009)",
 'Kongo (1932)',
 'Definitely, Maybe (2008)',
 'Jane Austen in Manhattan (1980)',
 'High Fidelity (2000)',
 'Letter, The (1929)',
 'Little Boy Blue (1997)',
 'Captivated (2014)',
 'Lovers of the Arctic Circle, The (Los Amantes del Círculo Polar) (1998)',
 'Alphabet Killer, The (2008)',
 'Flight of the Navigator (1986)',
 'Heartbeeps (1981)',
 'Apartment, The (1960)',
 'Wish You Were Here (1987)',
 'American: The Bill Hicks Story (2009)',
 'Wooden Crosses (Les croix de bois) (1932)',
 'Day Without a Mexican, A (2004)',
 'Over the Brooklyn Bridge (1984)',
 'Asphalt (1929)',
 'Shanghai Knights (2003)',
 'Dhoom (2004)',
 'Malcolm X (1992)',
 'Bad Santa (2003)',
 'Hucksters, The (1947)',
 'Dinner, The (Cena, La) (1998)',
 'Arsène Lupin (1932)',
 'Life of Emile Zola, The (1937)',
 'Phantom (2013)',
 'Coming Home (1978)',
 'Beavis and Butt-Head Do America (1996)',
 'Koch (2012)',
 'Trapped in Paradise (1994)',
 'Wings of Courage (1995)',
 'Christmas with the Kranks (2004)',
 'Gods of the Plague (Götter der Pest) (1970)',
 'Trinity: Gambling for High Stakes (Odds and Evens) (Pari e dispari) (1978)',
 'Gacy (2003)',
 "We All Loved Each Other So Much (C'eravamo tanto amati) (1974)",
 'Emperor (2012)',
 "I'm Not Scared (Io non ho paura) (2003)",
 'Gremlins (1984)',
 'Ruling Class, The (1972)',
 'Saint Ange (House of Voices) (2004)',
 'Wicker Man, The (1973)',
 'Heavy Weather (1995)',
 "Happily Ever After (Ils se marièrent et eurent beaucoup d'enfants) (2004)",
 '2001: A Space Odyssey (1968)',
 'Swamp, The (Ciénaga, La) (2001)',
 'Never Make It Home (2011)',
 'Juggernaut (1974)',
 'Teenage Mutant Ninja Turtles (1990)',
 'Possession (2002)',
 'Number 23, The (2007)',
 'Ulysses (Ulisse) (1954)',
 'Kiki (1926)',
 'Rise (2007)',
 'Keep, The (1983)',
 'Simon Birch (1998)',
 'Assassination Games (2011)',
 'Star Is Born, A (1954)',
 'Scoop (2006)',
 'Maternal Halfbrothers (Braca po materi) (1988)',
 'Tess (1979)',
 'Sex, Lies, and Videotape (1989)',
 'True Crime (1999)',
 'Visiting Hours (1982)',
 'Kangaroo Jack (2003)',
 'Uncle Marin, the Billionaire (Nea Marin miliardar) (Uncle Martin, the Multimillionaire) (1979)',
 'Farewell, My Lovely (1975)',
 'The Elephant Man (1982)',
 'Zatoichi and the Fugitives (Zatôichi hatashi-jô) (Zatôichi 18) (1968)',
 'A Chairy Tale (1957)',
 'Gummo (1997)',
 'Congress, The (1988)',
 'Best of Everything, The (1959)',
 'Along the Sungari River (Song hua jiang shang) (1947)',
 'War, Inc. (2008)',
 'Cell Count (2012)',
 'American Psycho (2000)',
 'Me Without You (2001)',
 'Mystery, Alaska (1999)',
 'Wuthering Heights (1939)',
 'Little Caesar (1931)',
 'Chisum (1970)',
 'Torrente 3: El protector (2005)',
 'Breaking the Girls (2013)',
 'Purge (Puhdistus) (2012)',
 'Escape From Tomorrow (2013)',
 'Beerfest (2006)',
 'My Awkward Sexual Adventure (2012)',
 'U2: Rattle and Hum (1988)',
 'Straw Dogs (2011)',
 'Seventh Continent, The (Der siebente Kontinent) (1989)',
 'Butterfly (La lengua de las mariposas) (1999)',
 'Pictures of the Old World (Obrazy starého sveta) (1972)',
 'Stricken (Er komt een vrouw bij de dokter) (2009)',
 'Death Wish 5: The Face of Death (1994)',
 'My Name Is Bruce (2007)',
 'Bigamist, The (1953)',
 'Dying at Grace (2003)',
 'Dream of Light (a.k.a. Quince Tree Sun, The) (Sol del membrillo, El) (1992)',
 "I'll See You in My Dreams (2015)",
 'Juror, The (1996)',
 'Plaisir, Le (1952)',
 'Touch the Top of the World (2006)',
 'Last Holiday (1950)',
 'Soviet Story, The (2008)',
 'Captain EO (1986)',
 'Wasp Woman, The (1959)',
 'Interview with the Assassin (2002)',
 'A Walk in the Old City of Warsaw (1958)',
 'Amazing Grace (2006)',
 'Gravity (Schwerkraft) (2009)',
 'City Hall (1996)',
 'Child, The (2012)',
 'I Am Jesus (2011)',
 'Stop! Or My Mom Will Shoot (1992)',
 'Birth (2004)',
 'Heiress, The (1949)',
 'Four Adventures of Reinette and Mirabelle (4 aventures de Reinette et Mirabelle) (1987)',
 'Wrong Guy, The (1997)',
 'Empire (1964)',
 'Merchants of Doubt (2014)',
 'Three Days of the Condor (3 Days of the Condor) (1975)',
 'Blind Menace, The (Shiranui kengyô) (1960)',
 'Trapped in the Closet: Chapters 1-12 (2005)',
 'Prime Suspect 2 (1992)',
 'Pontypool (2008)',
 'Children of a Lesser God (1986)',
 'Ganes (2007)',
 'Bugsy Malone (1976)',
 'Dimples (1936)',
 'Romasanta: The Werewolf Hunt (2004)',
 'Tevye (1939)',
 'The Thirteen Assassins (1963)',
 'After Fall, Winter (2011)',
 'Outpost (2008)',
 'Nativity! (2009)',
 'Whole Nine Yards, The (2000)',
 'One-Armed Swordsman, The (Dubei dao) (1967)',
 'Sea Wolf, The (1941)',
 'Criminal Life of Archibaldo de la Cruz, The (Ensayo de un crimen) (1955)',
 'Vera Cruz (1954)',
 'Citizen Cohn (1992)',
 'Melody Time (1948)',
 'Judge Priest (1934)',
 'Fight Club (1999)',
 'As I Was Moving Ahead Occasionally I Saw Brief Glimpses of Beauty (2000)',
 'Matrix Reloaded, The (2003)',
 'Finding Nemo (2003)',
 'Expendables 3, The (2014)',
 'Challenge to Lassie (1949)',
 'Zatoichi Meets the One-Armed Swordsman (Shin zatô Ichi: Yabure! Tôjin-ken) (Zatôichi 22) (1971)',
 'Assassin of the Tsar (1991)',
 'Roots (1977)',
 'Humble Pie (American Fork) (2007)',
 'City of Women, The (Città delle donne, La) (1980)',
 'Big (1988)',
 "Lightnin' (1925)",
 'Frankenstein (1931)',
 "Time Out (L'emploi du temps) (2001)",
 'Night Falls on Manhattan (1996)',
 'Kummeli Alivuokralainen (2008)',
 'Richie Rich (1994)',
 'Battle of China, The (Why We Fight, 6) (1944)',
 'Myra Breckinridge (1970)',
 'Looking for Lenny (2011)',
 'Bronco Billy (1980)',
 'Straight to Hell (1987)',
 'Black Tights (1-2-3-4 ou Les Collants noirs) (1960)',
 'Good Vibrations (2012)',
 'Certified Copy (Copie conforme) (2010)',
 'Divorcing Jack (1998)',
 'Sometimes They Come Back... Again (1996)',
 'Apollo 18 (2011)',
 'Sparrows (1926)',
 'Titanic (1953)',
 'Mendy: A Question of Faith (2003)',
 'Without Warning (1994)',
 'Lone Wolf and Cub: Sword of Vengeance (Kozure Ôkami: Kowokashi udekashi tsukamatsuru) (1972)',
 'Rocky Balboa (2006)',
 'What If (2013)',
 'Wolf Man, The (1941)',
 'Ugly Duckling and Me!, The (2006)',
 'Space Milkshake (2012)',
 'Sansho the Bailiff (Sanshô dayû) (1954)',
 'Night Shift (1982)',
 'Red Lights (Feux rouges) (2004)',
 'The Body (2012)',
 'Charley Varrick (1973)',
 "Since Otar Left (Depuis qu'Otar est parti...) (2003)",
 'Importance of Tying Your Own Shoes, The (Hur många lingon finns det i världen?) (2011)',
 'Dance with a Stranger (1985)',
 'Hot Rod (2007)',
 'Chuck Norris vs Communism (2015)',
 "Princess Ka'iulani (2009)",
 'Imagine That (2009)',
 'Death Race (2008)',
 'Topo, El (1970)',
 'Legend of Hell House, The (1973)',
 'Cosas que nunca te dije (Things I Never Told You) (1996)',
 'Wild China (2008)',
 'Ankur (The Seedling) (1974)',
 'Women in Love (1969)',
 'Tequila Sunrise (1988)',
 'Separate Tables (1958)',
 'Equinox Flower (Higanbana) (1958)',
 'Aelita: The Queen of Mars (Aelita) (1924)',
 'Mindhunters (2004)',
 'Live and Let Die (1973)',
 'Cars That Ate Paris, The (1974)',
 'Such a Long Journey (1998)',
 "Let's Go to Prison (2006)",
 'Into the West (1992)',
 'Descent, The (2005)',
 'Love & Sex (2000)',
 'Willard (2003)',
 'Steal a Pencil for Me (2007)',
 "Guess Who's Coming to Dinner (1967)",
 'Short Term 12 (2013)',
 'Outlaw, The (1943)',
 'Legend of Bagger Vance, The (2000)',
 'Habana Blues (2005)',
 'Strongest Man in the World, The (1975)',
 'DarkBlueAlmostBlack (Azuloscurocasinegro) (2006)',
 'Queen Kelly (1929)',
 'Shadow Puppets (2007)',
 'The Walking Hills (1949)',
 'All for the Winner (Dou sing) (1990)',
 'Barbershop 2: Back in Business (2004)',
 'Deal of the Century (1983)',
 'Play It Again, Sam (1972)',
 "Brewster's Millions (1985)",
 'Mrs. Winterbourne (1996)',
 'Commare secca, La (Grim Reaper, The) (1962)',
 'Scum (1979)',
 'Superman/Batman: Public Enemies (2009)',
 'Brother Minister: The Assassination of Malcolm X (1994)',
 'Ron Clark Story, The (2006)',
 "Angel of Mine (a.k.a. The Mark of an Angel) (L'empreinte de l'ange) (2008)",
 'Water Drops on Burning Rocks (2000)',
 'Men of Honor (2000)',
 'Hilton! (2013)',
 'Grace of My Heart (1996)',
 'Fortune Cookie, The (1966)',
 'Nightwatching (2007)',
 'Master of Ballantrae, The (1953)',
 'Möbius (2013)',
 'House of Seven Corpses, The (1974)',
 "Midsummer Night's Sex Comedy, A (1982)",
 'Do You Like Hitchcock? (Ti piace Hitchcock?) (2005)',
 'Red Riding: 1974 (2009)',
 'Boy Interrupted (2008)',
 'Day of the Outlaw (1959)',
 'Flatliners (1990)',
 'Cyrus (2010)',
 'Twilight Zone: The Movie (1983)',
 'Kopps (2003)',
 'Boiler Room (2000)',
 'Temptation of a Monk (You Seng) (1993)',
 'Saban, Son of Saban (1977)',
 'Soylent Green (1973)',
 'Hunters, The (1958)',
 'Green Man, The (1956)',
 'Goldene Zeiten (2006)',
 'Caesar Must Die (Cesare deve morire) (2012)',
 'Chicago (2002)',
 'Ladies in Retirement (1941)',
 'Disney Sing Along Songs: Under the Sea (1990)',
 'Balzac and the Little Chinese Seamstress (Xiao cai feng) (2002)',
 'Snow Flower and the Secret Fan (2011)',
 'Born to Be Bad (1950)',
 'John Mulaney: New In Town (2012)',
 'Wraith, The (1986)',
 'Contract, The (2006)',
 'Triple Cross (1966)',
 'Happy, Texas (1999)',
 'Saint Ralph (2004)',
 'Tracker (2010)',
 'No Regrets for Our Youth (Waga seishun ni kuinashi) (1946)',
 'Only the Young (2012)',
 'Zero Theorem, The (2013)',
 'Samurai Spy (Ibun Sarutobi Sasuke) (1965)',
 'Marriage Circle, The (1924)',
 'Chances Are (1989)',
 'Sleepover (2004)',
 'Wedding March, The (1928)',
 'Tex (1982)',
 'Intentions of Murder (a.k.a. Murderous Instincts) (Akai satsui) (1964)',
 'Chunhyang (2000)',
 'How I Live Now (2013)',
 'Die Hard 2 (1990)',
 'Dogtown and Z-Boyz (2001)',
 "Pandora's Box (Pandora'nin kutusu) (2008)",
 'Die, Monster, Die! (1965)',
 'Sushi Girl (2012)',
 'Leif (1987)',
 'Patterns (1956)',
 'Hansel & Gretel: Witch Hunters (2013)',
 'Burn, Witch, Burn (Night of the Eagle) (1962)',
 'Grace Is Gone (2007)',
 'Stations of the Cross (2014)',
 'Desert Blue (1999)',
 'Kauwboy (2012)',
 'Kids Are All Right, The (2010)',
 "Cutter's Way (1981)",
 'Divo, Il (2008)',
 'Sleepwalk with Me (2012)',
 'As I Lay Dying (2013)',
 "India's Daughter (2015)",
 'Hannah and Her Sisters (1986)',
 'Scotland, Pa. (2001)',
 'Are We Done Yet? (2007)',
 'Toys in the Attic (1963)',
 'Forces of Nature (1999)',
 'Rock of Ages (2012)',
 'Prairie Home Companion, A (2006)',
 'Shanghai Noon (2000)',
 'Boy A (2007)',
 'Odd Life of Timothy Green, The (2012)',
 'Dead Ringer (1964)',
 'Who Is Cletis Tout? (2001)',
 'Lady in Number 6: Music Saved My Life, The (2014)',
 'Food Matters (2008)',
 "Don't Look in the Basement! (1973)",
 'Children of Men (2006)',
 'Happy Event, A (Un Heureux Evénement) (2011)',
 'North (1994)',
 'Wrestling for Jesus: The Tale of T-Money (2011)',
 'Human Factor, The (1979)',
 'Boys Are Back, The (2009)',
 'Cinderella (1950)',
 'Ways to Live Forever (2010)',
 'Quatermass 2 (Enemy from Space) (1957)',
 'Another Country (1984)',
 "Inside: 'Dr. Strangelove or How I Learned to Stop Worrying and Love the Bomb' (2000)",
 'Inventing the Abbotts (1997)',
 'Man Called Peter, A (1955)',
 'Stanley & Iris (1990)',
 'Cecil B. DeMented (2000)',
 'Littlest Rebel, The (1935)',
 'Sound and Fury (2000)',
 'Two Days, One Night (Deux jours, une nuit) (2014)',
 'Subspecies IV: Bloodstorm (1998)',
 'Katy Perry: Part of Me (2012)',
 'Pacific Heights (1990)',
 "Wing and the Thigh, The (L'aile ou la cuisse) (1976)",
 'Righteous Kill (2008)',
 'Mummy: Tomb of the Dragon Emperor, The (2008)',
 'Neighbors (2014)',
 'Killing Floor, The (2007)',
 'Remember the Daze (Beautiful Ordinary, The) (2007)',
 'Gabriel Over the White House (1933)',
 'Casanova (2005)',
 'Unmistaken Child (2008)',
 'My Boy Jack (2007)',
 'Black Gold (2006)',
 'Pokémon the Movie 2000 (2000)',
 'How Wang-Fo Was Saved (Comment Wang-Fo fut sauvé) (1987)',
 'Monsters vs Aliens: Mutant Pumpkins from Outer Space (2009)',
 'Nightmare Before Christmas, The (1993)',
 'Indie Game: The Movie (2012)',
 'Invaders from Mars (1986)',
 'They Made Me a Criminal (I Became a Criminal) (They Made Me a Fugitive) (1939)',
 'Cockfighter (1974)',
 'How to Be (2008)',
 'Lake of Fire (2006)',
 'Jesse Stone: Stone Cold (2005)',
 'Easy Money (1983)',
 'Spaghetti West, The (2005)',
 'For the Moment (1994)',
 'Puzzlehead (2005)',
 'Harmonists, The (1997)',
 'Happiness Is in the Field (Bonheur est dans le pré, Le) (1995)',
 'Antoine and Colette (Antoine et Colette) (1962)',
 'Three Comrades (1938)',
 'Nights of Cabiria (Notti di Cabiria, Le) (1957)',
 'Second Skin (Segunda Piel) (1999)',
 'Civil Brand (2002)',
 'Make Way for Tomorrow (1937)',
 'Bread and Roses (2000)',
 'Boomerang (1992)',
 'SLC Punk! (1998)',
 "Passion of Love (Passione d'amore) (1981)",
 'Battered Bastards of Baseball, The (2014)',
 'Exorcism of Emily Rose, The (2005)',
 'Very Brady Sequel, A (1996)',
 'Africa addio (1966)',
 'Comet in Moominland (1992)',
 'Snow Angels (2007)',
 'Tigerland (2000)',
 'Loins of Punjab Presents (2007)',
 'Evil That Men Do, The (1984)',
 'Mad Bastards (2010)',
 'Everest (1998)',
 'Mystery Street (1950)',
 'Samson and Delilah (2009)',
 'Reflections in a Golden Eye (1967)',
 'Below (2002)',
 'Chronicle of a Disappearance (1996)',
 'Joneses, The (2009)',
 'Slither (2006)',
 'Only the Strong (1993)',
 'Rage at Dawn (1955)',
 'Love in the Time of Cholera (2007)',
 'Catacombs (2007)',
 'Adventure in Space and Time, An (2013)',
 'The Gilded Cage (2013)',
 'Action in the North Atlantic (1943)',
 'Selfish Giant, The (2013)',
 'Toys (1992)',
 'Chess Players, The (Shatranj Ke Khilari) (1977)',
 'Virginity Hit, The (2010)',
 "Whole Town's Talking, The (Passport to Fame) (1935)",
 'Borrowers, The (2011)',
 'Walk Hard: The Dewey Cox Story (2007)',
 'Dead Set (2008)',
 'Life During Wartime (2009)',
 'Haunting of Molly Hartley, The (2008)',
 'Tropical Malady (Sud pralad) (2004)',
 'Land Ho! (2014)',
 'Lords of Flatbush, The (1974)',
 'Tae Guk Gi: The Brotherhood of War (Taegukgi hwinalrimyeo) (2004)',
 "Tyler Perry's Temptation: Confessions of a Marriage Counselor (2013)",
 'Girls, Les (1957)',
 'Woman, The (2011)',
 'Kiss Me, Guido (1997)',
 'Last Night (2010)',
 'Hunk (1987)',
 'Night of the Living Dead (1968)',
 'Gabby Douglas Story, The (2014)',
 "I Can't Think Straight (2007)",
 'Mishima: A Life in Four Chapters (1985)',
 'Duets (2000)',
 'Holiday Spin (2012)',
 'Creepshow (1982)',
 'American Carol, An (2008)',
 'Underground: The Julian Assange Story (2012)',
 'Szamanka (1996)',
 'Most Hated Family in America, The (2007)',
 'White of the Eye (1987)',
 'Imagine Me & You (2005)',
 'Monsieur Ibrahim (Monsieur Ibrahim et les fleurs du Coran) (2003)',
 'Wrong (2012)',
 'Blonde Crazy (1931)',
 'Generale Della Rovere, Il (1959)',
 'Bounty Killer (2013)',
 'Wonder Woman (2009)',
 'Making Contact (a.k.a. Joey) (1985)',
 'Swing Shift (1984)',
 'Snow Cake (2006)',
 'Conquest, The (La conquête) (2011)',
 'Lady Jane (1986)',
 'Superpower (2008)',
 'Punk Singer, The (2013)',
 "Futurama: Bender's Big Score (2007)",
 'Abandoned, The (2006)',
 'Gone (2012)',
 'Bikini Beach (1964)',
 'Canal, The (2014)',
 'Kaena: The Prophecy (Kaena: La prophétie) (2003)',
 'Future, The (2011)',
 'Taxi 2 (2000)',
 'Wrong Turn (2003)',
 'Informant!, The (2009)',
 'Bulletproof (1996)',
 'Eat Sleep Die (Äta sova dö) (2012)',
 "Who's Singin' Over There? (a.k.a. Who Sings Over There) (Ko to tamo peva) (1980)",
 'Whole (2003)',
 'Funny Games (1997)',
 'What Maisie Knew (2012)',
 'Boots and Saddles (1937)',
 'Love the Hard Way (2001)',
 'Trust Us, This Is All Made Up (2009)',
 'Sgt. Bilko (1996)',
 'Dark Girls (2011)',
 'Whatever Happened to Aunt Alice? (1969)',
 'Round Up, The (La Rafle) (2010)',
 'Aftershock (Tangshan dadizhen) (2010)',
 'Haunted House, A (2013)',
 'Crazy on the Outside (2010)',
 'Barbary Coast (1935)',

In [153]:
from rapidfuzz import process , fuzz
match = process.extractOne("Are", all_titles , scorer=fuzz.WRatio , score_cutoff=80 , )

In [170]:
process.extract("Are You Here", all_titles , scorer=fuzz.WRatio , score_cutoff=70 , limit=7)

[('Are You Here (2014)', 90.0, 5),
 ("You Can't Win 'Em All (1970)", 85.5, 84),
 ('Wish You Were Here (1987)', 85.5, 145),
 ('Me Without You (2001)', 85.5, 211),
 ("I'll See You in My Dreams (2015)", 85.5, 233),
 ('Do You Like Hitchcock? (Ti piace Hitchcock?) (2005)', 85.5, 382),
 ('Chances Are (1989)', 85.5, 416)]

In [154]:
match

('Are You Here (2014)', 90.0, 5)

In [143]:
import difflib

user_input = "Cercle Rouge, Le"

matches = difflib.get_close_matches(user_input , all_titles , n=3)

In [144]:
matches

[]