In [1]:
!unzip archive.zip

Archive:  archive.zip
  inflating: genome_scores.csv
  inflating: genome_tags.csv
  inflating: link.csv
  inflating: movie.csv
  inflating: rating.csv
  inflating: tag.csv

## Popularity Based Recommendation System

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [20]:
moives_data = pd.read_csv("app/data/movie.csv").sample(frac=0.5 , random_state=42)

In [21]:
moives_data.head()

       movieId                      title                             genres
12922    61116        Black Caesar (1973)                        Crime|Drama
14085    70697             G-Force (2009)  Action|Adventure|Children|Fantasy
23517   111931                Raze (2013)                      Action|Horror
8960     26630          Moonwalker (1988)                            Musical
13152    63692  Don Q Son of Zorro (1925)                  Adventure|Romance

In [22]:
moives_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 13639 entries, 12922 to 16177
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   movieId  13639 non-null  int64
 1   title    13639 non-null  object
 2   genres   13639 non-null  object
dtypes: int64(1), object(2)
memory usage: 426.2+ KB

In [23]:
rating_data = pd.read_csv("app/data/rating.csv").sample(frac=0.5 , random_state=42)

In [24]:
rating_data.head()

          userId  movieId  rating            timestamp
17679788  122270     8360     3.5  2012-04-22 01:07:04
7106385    49018       32     2.0  2001-09-11 07:50:36
12970708   89527   109374     3.5  2015-01-06 09:26:40
15426752  106704     1060     3.0  2000-01-22 21:27:57
6934678    47791     1732     2.0  2006-01-19 15:48:23

In [25]:
movie_data = pd.merge(rating_data , moives_data , on="movieId")

In [26]:
movie_data.head()

,userId,movieId,rating,timestamp,title,genres
0,49018,32,2.0,2001-09-11 07:50:36,Twelve Monkeys (a.k.a. 12 Monkeys) (1995),Mystery|Sci-Fi|Thriller
1,89527,109374,3.5,2015-01-06 09:26:40,"Grand Budapest Hotel, The (2014)",Comedy|Drama
2,11304,504,1.0,2003-05-01 17:20:18,No Escape (1994),Action|Drama|Sci-Fi
3,49851,1792,2.5,2003-08-04 02:41:55,U.S. Marshals (1998),Action|Crime|Thriller
4,40721,32213,4.0,2015-02-01 01:01:04,Cube Zero (2004),Horror|Mystery|Sci-Fi|Thriller

In [27]:
movie_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5076577 entries, 0 to 5076576
Data columns (total 6 columns):
 #   Column     Dtype
---  ------     -----
 0   userId     int64
 1   movieId    int64
 2   rating     float64
 3   timestamp  object
 4   title      object
 5   genres     object
dtypes: float64(1), int64(2), object(3)
memory usage: 232.4+ MB

## Criteria For Popularity Based Recommendation

### The Criteria is based on:
  #### 1. Moives with the Highest rating
  #### 2. NUmber of Views

### Average rating of moives

In [28]:
movie_data['title'].value_counts()

title
Pulp Fiction (1994)                                                       33658
Shawshank Redemption, The (1994)                                          31488
Jurassic Park (1993)                                                      29808
Star Wars: Episode IV - A New Hope (1977)                                 27284
Toy Story (1995)                                                          24874
                                                                          ...
Loft (Rofuto) (2005)                                                          1
Cinema Komunisto (2010)                                                       1
Chronicle of the Years of Fire (Chronique des années de braise) (1975)        1
Springfield Rifle (1952)                                                      1
Crime at the Chinese Restaurant (1981)                                        1
Name: count, Length: 12002, dtype: int64

In [29]:
movie_data.groupby('title')['rating'].mean().head()

title
$9.99 (2008)                                      3.090909
$ellebrity (Sellebrity) (2012)                    0.500000
'Hellboy': The Seeds of Creation (2004)           3.022727
'Human' Factor, The (Human Factor, The) (1975)    1.000000
'Neath the Arizona Skies (1934)                   2.031250
Name: rating, dtype: float64

In [30]:
movie_data.groupby('title')['rating'].mean().sort_values(ascending=False).head(20)

title
Linotype: The Film (2012)                                             5.0
Warm December, A (1973)                                               5.0
Boy Meets Boy (2008)                                                  5.0
Breaking the Silence: Truth and Lies in the War on Terror (2003)      5.0
Schmatta: Rags to Riches to Rags (2009)                               5.0
Heartbeats (Kohtaamisia) (2009)                                       5.0
Kevin Smith: Too Fat For 40 (2010)                                    5.0
Echoes of the Rainbow (Sui yuet san tau) (2010)                       5.0
Doctor and the Devils, The (1985)                                     5.0
Best of Ernie and Bert, The (1988)                                    5.0
Miranda (1948)                                                        5.0
Mishen (Target) (2011)                                                5.0
Turkish Dance, Ella Lola (1898)                                       5.0
Hellhounds on My Trail (1999)                                         5.0
Drew: The Man Behind the Poster (2013)                                5.0
Inquire Within (2012)                                                 5.0
Pursuit of Unhappiness, The (Anleitung zum Unglücklichsein) (2012)    5.0
Play Girl (1941)                                                      5.0
Day the Universe Changed, The (1985)                                  5.0
A Gun for Jennifer (1997)                                             5.0
Name: rating, dtype: float64

In [31]:
movie_data.groupby('title')['rating'].count().sort_values(ascending=False).head()

title
Pulp Fiction (1994)                          33658
Shawshank Redemption, The (1994)             31488
Jurassic Park (1993)                         29808
Star Wars: Episode IV - A New Hope (1977)    27284
Toy Story (1995)                             24874
Name: rating, dtype: int64

In [32]:
popularity_data = movie_data[['title' , 'rating']]

In [33]:
popularity_data = movie_data[['title' , 'rating']]

In [34]:
popularity_data

                                             title  rating
0        Twelve Monkeys (a.k.a. 12 Monkeys) (1995)     2.0
1                 Grand Budapest Hotel, The (2014)     3.5
2                                 No Escape (1994)     1.0
3                             U.S. Marshals (1998)     2.5
4                                 Cube Zero (2004)     4.0
...                                            ...     ...
5076572                     American Dreamz (2006)     3.0
5076573                     American Beauty (1999)     4.5
5076574              Amityville Horror, The (1979)     2.0
5076575                Escape from New York (1981)     3.0
5076576                        Runaway Jury (2003)     4.0

[5076577 rows x 2 columns]

#### calcualte the average ratings

In [35]:
rating_mean_count = pd.DataFrame(popularity_data.groupby('title')['rating'].mean())
rating_mean_count

                                                  rating
title
$9.99 (2008)                                    3.090909
$ellebrity (Sellebrity) (2012)                  0.500000
'Hellboy': The Seeds of Creation (2004)         3.022727
'Human' Factor, The (Human Factor, The) (1975)  1.000000
'Neath the Arizona Skies (1934)                 2.031250
...                                                  ...
¡Qué hacer! (1970)                              3.000000
¡Three Amigos! (1986)                           3.102146
À nos amours (1983)                             3.650000
À propos de Nice (1930)                         3.333333
Árido Movie (2005)                              2.000000

[12002 rows x 1 columns]

#### Calculate the count of ratings and add to the average ratings above

In [36]:
rating_mean_count['rating_counts'] = pd.DataFrame(popularity_data.groupby('title')['rating'].count())

In [54]:
rating_mean_count.describe()

             rating  rating_counts
count  12002.000000   12002.000000
mean       3.157582     422.977587
std        0.672271    1635.344279
min        0.500000       1.000000
25%        2.800000       3.000000
50%        3.200000      16.000000
75%        3.600000     139.000000
max        5.000000   33658.000000

In [42]:
rating_mean_count.head()

                                                rating  rating_counts
title
$9.99 (2008)                                       3.1             22
$ellebrity (Sellebrity) (2012)                     0.5              1
'Hellboy': The Seeds of Creation (2004)            3.0             44
'Human' Factor, The (Human Factor, The) (1975)     1.0              1
'Neath the Arizona Skies (1934)                    2.0             16

In [43]:
rating_mean_count['rating'] = round(rating_mean_count['rating'] , 1)

In [44]:
rating_mean_count.head()

                                                rating  rating_counts
title
$9.99 (2008)                                       3.1             22
$ellebrity (Sellebrity) (2012)                     0.5              1
'Hellboy': The Seeds of Creation (2004)            3.0             44
'Human' Factor, The (Human Factor, The) (1975)     1.0              1
'Neath the Arizona Skies (1934)                    2.0             16

In [59]:
rating_popularity =  rating_mean_count[(rating_mean_count['rating'] > 4)& (rating_mean_count['rating_counts'] > 15000)]

In [60]:
rating_popularity

                                               rating  rating_counts
title
American Beauty (1999)                            4.2          22401
Fight Club (1999)                                 4.2          19957
Godfather, The (1972)                             4.4          20693
Lord of the Rings: The Two Towers, The (2002)     4.1          16895
Memento (2000)                                    4.2          15329
Monty Python and the Holy Grail (1975)            4.2          16512
Pulp Fiction (1994)                               4.2          33658
Saving Private Ryan (1998)                        4.1          18680
Seven (a.k.a. Se7en) (1995)                       4.1          21605
Shawshank Redemption, The (1994)                  4.4          31488
Sixth Sense, The (1999)                           4.1          19362
Star Wars: Episode IV - A New Hope (1977)         4.2          27284
Usual Suspects, The (1995)                        4.3          23436

In [61]:
rating_popularity = rating_popularity.sort_values(by='rating' , ascending=False)
rating_popularity

                                               rating  rating_counts
title
Godfather, The (1972)                             4.4          20693
Shawshank Redemption, The (1994)                  4.4          31488
Usual Suspects, The (1995)                        4.3          23436
American Beauty (1999)                            4.2          22401
Fight Club (1999)                                 4.2          19957
Star Wars: Episode IV - A New Hope (1977)         4.2          27284
Memento (2000)                                    4.2          15329
Monty Python and the Holy Grail (1975)            4.2          16512
Pulp Fiction (1994)                               4.2          33658
Lord of the Rings: The Two Towers, The (2002)     4.1          16895
Saving Private Ryan (1998)                        4.1          18680
Seven (a.k.a. Se7en) (1995)                       4.1          21605
Sixth Sense, The (1999)                           4.1          19362